<?php

namespace Dancycodes\Gale\Http;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Cache;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * GaleDownloadServeController — Serves signed Gale download tokens (F-039)
 *
 * Validates the HMAC-signed token generated by GaleResponse::download(),
 * verifies the token has not expired, then streams the file to the browser
 * with appropriate Content-Disposition and Content-Type headers.
 *
 * Route: GET /gale/download/{token}
 * Registered by GaleServiceProvider.
 *
 * Security:
 * - Token is HMAC-SHA256 signed with app.key — cannot be forged
 * - 5-minute expiry enforced server-side in the cache payload
 * - Authentication is enforced by standard Laravel middleware on the caller's route;
 *   the download token itself is a short-lived capability token (BR-039.9)
 */
class GaleDownloadServeController extends Controller
{
    /**
     * Serve a file download for a signed Gale download token
     *
     * @param  Request  $request
     * @param  string  $token  Signed token (token.signature)
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function serve(Request $request, string $token): mixed
    {
        // Split token from signature
        $dotPos = strrpos($token, '.');
        if ($dotPos === false) {
            abort(403, 'Invalid download token.');
        }

        $rawToken = substr($token, 0, $dotPos);
        $signature = substr($token, $dotPos + 1);

        // Verify HMAC signature
        $expectedSig = hash_hmac('sha256', $rawToken, config('app.key'));
        if (! hash_equals($expectedSig, $signature)) {
            abort(403, 'Download token signature mismatch.');
        }

        // Retrieve payload from cache
        $cacheKey = 'gale_download:'.$rawToken;
        $payload = Cache::get($cacheKey);

        if ($payload === null) {
            abort(404, 'Download token expired or not found.');
        }

        // Verify server-side expiry (belt-and-suspenders beyond cache TTL)
        if (! isset($payload['expires']) || time() > $payload['expires']) {
            Cache::forget($cacheKey);
            abort(410, 'Download token has expired.');
        }

        // One-time use: remove from cache immediately
        Cache::forget($cacheKey);

        $filename = $payload['filename'] ?? 'download';
        $mimeType = $payload['mime'] ?? null;
        $filePath = $payload['path'] ?? null;
        $content = $payload['content'] ?? null;
        $isTmp = $payload['is_tmp'] ?? false;

        // Auto-detect MIME type if not provided
        if ($mimeType === null) {
            $mimeType = $this->detectMimeType($filename, $filePath, $content);
        }

        // BR-039.7: Stream the file without loading into memory (for file paths)
        if ($filePath !== null && file_exists($filePath)) {
            return $this->streamFile($filePath, $filename, $mimeType, $isTmp);
        }

        // Fallback: serve from raw content string
        if ($content !== null) {
            return $this->streamContent($content, $filename, $mimeType);
        }

        abort(404, 'Download content not found.');
    }

    /**
     * Stream a file from disk with Content-Disposition: attachment
     *
     * Uses Laravel's StreamedResponse to avoid loading the entire file into memory (BR-039.7).
     *
     * @param  string  $filePath  Absolute path to the file
     * @param  string  $filename  Download filename for the browser
     * @param  string  $mimeType  Content-Type header value
     * @param  bool  $deleteAfter  Whether to delete the file after serving (for temp files)
     * @return \Symfony\Component\HttpFoundation\StreamedResponse
     */
    protected function streamFile(string $filePath, string $filename, string $mimeType, bool $deleteAfter = false): StreamedResponse
    {
        $fileSize = filesize($filePath);

        $response = new StreamedResponse(function () use ($filePath, $deleteAfter): void {
            try {
                $handle = fopen($filePath, 'rb');
                if ($handle === false) {
                    return;
                }

                while (! feof($handle)) {
                    echo fread($handle, 8192);
                    flush();
                }

                fclose($handle);
            } finally {
                if ($deleteAfter && file_exists($filePath)) {
                    @unlink($filePath);
                }
            }
        });

        $this->applyDownloadHeaders($response, $filename, $mimeType, $fileSize ?: null);

        return $response;
    }

    /**
     * Stream raw content string as a download
     *
     * @param  string  $content   Raw file content
     * @param  string  $filename  Download filename for the browser
     * @param  string  $mimeType  Content-Type header value
     * @return \Symfony\Component\HttpFoundation\StreamedResponse
     */
    protected function streamContent(string $content, string $filename, string $mimeType): StreamedResponse
    {
        $contentLength = strlen($content);

        $response = new StreamedResponse(function () use ($content): void {
            echo $content;
            flush();
        });

        $this->applyDownloadHeaders($response, $filename, $mimeType, $contentLength);

        return $response;
    }

    /**
     * Apply standard download headers to a response (BR-039.2)
     *
     * Sets Content-Disposition: attachment, Content-Type, and optional Content-Length.
     * Filename is URL-encoded in the RFC 5987 extended parameter for Unicode support.
     *
     * @param  StreamedResponse  $response
     * @param  string  $filename
     * @param  string  $mimeType
     * @param  int|null  $contentLength
     */
    protected function applyDownloadHeaders(
        StreamedResponse $response,
        string $filename,
        string $mimeType,
        ?int $contentLength
    ): void {
        // RFC 5987: encode unicode filenames in Content-Disposition
        $encodedFilename = rawurlencode($filename);
        $asciiFilename = preg_replace('/[^\x20-\x7E]/', '_', $filename) ?? $filename;

        $response->headers->set('Content-Type', $mimeType);
        $response->headers->set(
            'Content-Disposition',
            "attachment; filename=\"{$asciiFilename}\"; filename*=UTF-8''{$encodedFilename}"
        );
        $response->headers->set('Cache-Control', 'private, no-store');
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        if ($contentLength !== null && $contentLength > 0) {
            $response->headers->set('Content-Length', (string) $contentLength);
        }
    }

    /**
     * Auto-detect MIME type from filename extension or file path
     *
     * @param  string  $filename  Download filename
     * @param  string|null  $filePath  Absolute file path (for finfo detection)
     * @param  string|null  $content  Raw content (not used for detection)
     * @return string MIME type string
     */
    protected function detectMimeType(string $filename, ?string $filePath, ?string $content): string
    {
        // Try finfo for file path detection (most accurate)
        if ($filePath !== null && file_exists($filePath) && function_exists('finfo_open')) {
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            if ($finfo !== false) {
                $detected = finfo_file($finfo, $filePath);
                finfo_close($finfo);
                if ($detected !== false && $detected !== '') {
                    return $detected;
                }
            }
        }

        // Fall back to extension-based detection
        $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

        return match ($ext) {
            'pdf'  => 'application/pdf',
            'csv'  => 'text/csv',
            'txt'  => 'text/plain',
            'json' => 'application/json',
            'xml'  => 'application/xml',
            'zip'  => 'application/zip',
            'gz'   => 'application/gzip',
            'tar'  => 'application/x-tar',
            'xls'  => 'application/vnd.ms-excel',
            'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'doc'  => 'application/msword',
            'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'png'  => 'image/png',
            'jpg', 'jpeg' => 'image/jpeg',
            'gif'  => 'image/gif',
            'svg'  => 'image/svg+xml',
            'mp4'  => 'video/mp4',
            'mp3'  => 'audio/mpeg',
            default => 'application/octet-stream',
        };
    }
}
