<?php

namespace Dancycodes\Gale\Routing\PendingRouteTransformers;

use Dancycodes\Gale\Routing\Attributes\Group;
use Dancycodes\Gale\Routing\PendingRoutes\PendingRoute;
use Dancycodes\Gale\Routing\PendingRoutes\PendingRouteAction;
use Illuminate\Support\Collection;

/**
 * Group Attribute Name Prefix Transformer
 *
 * Applies the `as` (name prefix) setting from the #[Group] attribute to all
 * route names after they have been auto-generated by AddDefaultRouteName.
 *
 * This transformer runs AFTER AddDefaultRouteName so that both explicitly named
 * routes (via #[Route(name:)]) and auto-generated route names both receive
 * the group name prefix.
 *
 * Example:
 *   #[Group(prefix: '/api/v1', as: 'api.v1.')]
 *   public function index()  ->  route name: 'api.v1.api.v1.index' (auto-generated)
 *
 * The transformer simply prepends the `as` string to whatever name each action
 * already has. If an action has no name (null), the prefix is not applied.
 *
 * @see \Dancycodes\Gale\Routing\Attributes\Group
 * @see \Dancycodes\Gale\Routing\PendingRouteTransformers\HandleGroupAttribute
 * @see \Dancycodes\Gale\Routing\PendingRouteTransformers\AddDefaultRouteName
 */
class HandleGroupNamePrefix implements PendingRouteTransformer
{
    /**
     * Transform pending routes by prepending the group name prefix to all route names
     *
     * Only applies to controllers with a #[Group(as: '...')] attribute. Prepends
     * the `as` value to each action's current name (whether explicit or auto-generated).
     * Actions with no name are skipped.
     *
     * @param Collection<int, PendingRoute> $pendingRoutes Pending routes to transform
     *
     * @return Collection<int, PendingRoute> Transformed pending routes with prefixed names
     */
    public function transform(Collection $pendingRoutes): Collection
    {
        $pendingRoutes->each(function (PendingRoute $pendingRoute) {
            $groupAttribute = $pendingRoute->getAttribute(Group::class);

            if (!$groupAttribute instanceof Group) {
                return;
            }

            if ($groupAttribute->as === null || $groupAttribute->as === '') {
                return;
            }

            $namePrefix = $groupAttribute->as;

            $pendingRoute->actions->each(function (PendingRouteAction $action) use ($namePrefix) {
                if ($action->name === null) {
                    return;
                }

                $action->name = $namePrefix . $action->name;
            });
        });

        return $pendingRoutes;
    }
}
